### ISSUE TITLE
Multicolor with Special ASCii characters only shows first color

### ISSUE THREAD

**Issue by nooitaf** [NURDspace/rpi-rgb-led-matrix#1]
irc command:
```
!ticker $CFF0000$█$C00FF00$█$C0000FF$█
```
result: 1 red block
expected: 1 red, 1 green and 1 blue block

**Comment by ghost** [comment]
indeed it does
with $CFF0000$A$C00FF00$B$C0000FF$C
 it works fine
strange

**Comment by ghost** [comment]
fixed in abcdf18fd6e51a22fba1967bb9cb6cd4c13c7157
